name: kalavedika
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  modal_progress_hud: ^0.1.3
  cloud_firestore: ^0.13.5
  font_awesome_flutter: ^8.8.1
  edge_alert: ^0.0.1
  rflutter_alert: ^1.0.3
  youtube_player_flutter: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
  - images/
  fonts:
    - family: Courgette
      fonts:
        - asset: fonts/Courgette.ttf
    - family: Museo
      fonts:
        - asset: fonts/MuseoModer.ttf
    - family: Architects
      fonts:
        - asset: fonts/Architects.ttf



